# Generated by Django 2.2.4 on 2019-09-18 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('sets', models.IntegerField()),
                ('set_rest', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('rep_rest_absolute', models.BooleanField()),
                ('absolute_rep_rest', models.IntegerField()),
                ('work_ratio', models.IntegerField()),
                ('rest_ratio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('video', models.URLField(max_length=1024)),
                ('difficulty', models.CharField(choices=[('BEG', 'Begginer'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='INT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('exercises', models.ManyToManyField(to='workout.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='movements',
            field=models.ManyToManyField(to='workout.Movement'),
        ),
    ]
