# Generated by Django 2.2.4 on 2019-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_movement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default='described', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.CharField(default='described', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='difficulty',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='INT', max_length=3),
        ),
    ]
