# Generated by Django 2.2.4 on 2019-09-30 15:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('workout', '0004_auto_20190930_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Module',
        ),
    ]
