# Generated by Django 2.2.4 on 2019-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20190930_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='absolute_rep_rest',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_ratio',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set_rest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='work_ratio',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
