# Generated by Django 2.2.4 on 2019-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20190930_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='video',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
