# Generated by Django 2.2.4 on 2019-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20191009_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rep_rest_absolute',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='exercise',
            name='rep_length',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ConditioningMovement',
        ),
    ]
