# Generated by Django 2.2.4 on 2019-10-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_auto_20191009_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='unilateral',
            field=models.BooleanField(default=False),
        ),
    ]
