# Generated by Django 2.2.4 on 2019-11-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_auto_20191115_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energysystem',
            old_name='activation_start',
            new_name='activation',
        ),
        migrations.RenameField(
            model_name='energysystem',
            old_name='recovery_time',
            new_name='recovery',
        ),
    ]
