# Generated by Django 2.2.4 on 2019-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_auto_20191118_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='TrainingDay',
        ),
        migrations.CreateModel(
            name='Microcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('days', models.IntegerField(default=7)),
                ('modules', models.ManyToManyField(to='workout.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('microcycles', models.ManyToManyField(to='workout.Microcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Macrocycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('days', models.IntegerField(default=90)),
                ('fitness_components', models.ManyToManyField(to='workout.FitnessComponent')),
                ('mesocycles', models.ManyToManyField(to='workout.Mesocycle')),
            ],
        ),
    ]
