# Generated by Django 2.2.4 on 2019-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_auto_20191126_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrocycle',
            name='fitness_components',
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='days',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='fitness_components',
            field=models.ManyToManyField(to='workout.FitnessComponent'),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='days',
            field=models.IntegerField(default=180),
        ),
    ]
